### ISSUE TITLE
Where did the docs go?

### ISSUE THREAD

**Issue by mitchell-laveto** [Pluxbox/radiomanager-php-client#1]
We were working with the SDK and were using Github to read the docs.

Now everything is gone. What happened? Status updates please.

**Comment by thecas** [comment]
Hi Mitchell,

We just deployed a wrong release, the correct one is deployed and available
again.

Sincerely,

*Caspar Adriani*


2017-08-14 16:19 GMT+02:00 mitchell-laveto <notifications@github.com>:

**Comment by mitchell-laveto** [comment]
Thank you for the update Cas. I will close this issue now.
