### ISSUE TITLE
How to set order of items

### ISSUE THREAD

**Issue by mitchell-laveto** [Pluxbox/radiomanager-php-client#2]
How can we set the order of the items? I don't see a column in https://github.com/Pluxbox/radiomanager-php-client/blob/master/docs/Model/Item.md which can do this.

How would you recommend we do this?

**Comment by Siebe** [comment]
Hello Mitchell,

You should look at the _previous_id column found in https://github.com/Pluxbox/radiomanager-php-client/blob/master/docs/Model/ItemDataInput.md
Here you can enter the ID of another item where the posted/updated item should be placed after.
Note: I've just updated it, as the field was missing an underscore. It should work now.

**Comment by mitchell-laveto** [comment]
Hi Siebe,

Just letting you know that providing the `_previous_id` worked.

I will close this issue now.
