### ISSUE TITLE
external_id cast to int

### ISSUE THREAD

**Issue by mitchell-laveto** [Pluxbox/radiomanager-php-client#3]
The `external_id` is being cast to int, it is supposed to be a string, this is how we store it as well and this worked before we used the SDK.

**Comment by mitchell-laveto** [comment]
@Siebe can you look at this?

**Comment by Siebe** [comment]
Hello Mitchell,

Apologies for the late reaction. This field should indeed be a string. I will try to release the SDK's again somewhere this week with a fix.

**Comment by Siebe** [comment]
@mitchell-laveto,
I've updated the SDK. The external_id field was also set on "required" for the post/patch operation of an Item. It is actually only required when posting it as "current" item, so I've adapted that as well.
