### ISSUE TITLE
Block current broken?

### ISSUE THREAD

**Issue by mitchell-laveto** [Pluxbox/radiomanager-php-client#4]
https://staging.radiomanager.pluxbox.com/api/v2/blocks/current comes back with a 404?

This wasn't before, I used this to create items in the current block when there weren't any yet.

**Comment by Siebe** [comment]
Hi Mitchell,

That endpoint will return a 404 if there is no current block or any blocks in the future, could that be the case? The return message in that case would be "Object not found"
